version: "3"

services:
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  hello-service:
    build: ./hello-service
    ports:
      - "8888:8888"
    environment:
      JAEGER_HOST: jaeger
      PG_HOST: db-postgres
    links:
      - jaeger
      - db-postgres

  greetings-service:
    build: ./greetings-service
    ports:
      - "8080:8080"
    environment:
      HELLO_SERVICE_HOST: hello-service
      JAEGER_HOST: jaeger
      PG_HOST: db-postgres
    links:
       - hello-service
       - jaeger
       - db-postgres

  db-postgres:
    image: "postgres:11.3"
    container_name: "db-postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg_dbdata:/usr/local/var/postgres
      - ./custom/postgresql.conf:/etc/postgresql.conf
      # - ./defaultpostgresql.conf:/etc/postgresql.conf
    command: postgres -c config_file=/etc/postgresql.conf # custom config leads to startup failure of IPv6
      
volumes:
  pg_dbdata:




