server:
  port: 8888

tracing:
  jaegerUrl: http://${JAEGER_HOST}:14268/api/traces
  

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

